baseurl: /badass2024

# Site settings
title: BADASS
email: your-email@domain.com
description: "BADASS 2024 is an international workshop on Bridging AI and Data-centric Systems co-located with ADBIS 2024."

# Team names, titles and social links
people:
- name: Julien Aligon
  pic: JA
  position: IRIT - University Toulouse Capitole (France)
  social:
    - title: at
      url: "julien.aligon@irit.fr"
- name: Anton Dignos
  pic: AD
  position: Free University of Bozen-Bolzano (Italy)
  social:
    - title: at
      url: "anton.dignoes@unibz.it"
- name: Elodie Escriva
  pic: EE
  position: IRIT - University Toulouse Capitole (France)
  social:
    - title: at
      url: "elodie.escriva@irit.fr"
- name: Matteo Francia
  pic: MF
  position: DISI - University of Bologna (Italy)
  social:
    - title: university
      url: https://www.unibo.it/sitoweb/m.francia/en
    - title: at
      url: "mailto:m.francia@unibo.it"
    - title: linkedin
      url: https://www.linkedin.com/in/matteo-francia/
- name: Nicolas Labroche
  pic: NL
  position: LIFAT - University of Tours (France)
  social:
    - title: at
      url: "nicolas.labroche@univ-tours.fr"
- name: Patrick Marcel
  pic: PM
  position: LIFO - University of Orléans (France)
  social:
    - title: university
      url: http://www.info.univ-tours.fr/~marcel/
    - title: at
      url: "mailto:patrick.marcel@univ-orleans.fr"
    - title: linkedin
      url: https://www.linkedin.com/in/patrick-marcel-58b42534/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: 
- title: facebook
  url: https://www.facebook.com/sharer/sharer.php?u=big.csr.unibo.it/BADASS2024
- title: linkedin
  url: https://www.linkedin.com/shareArticle?url=big.csr.unibo.it/BADASS2024

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
